version: "3"
services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: open-source-success-gpu-app
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
      - ./app:/app
    restart: unless-stopped
