services:
  web:
    build:
      context: .
      dockerfile: ./docker/App_Dockerfile
    container_name: open-source-success-presentation-webapp-app
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: ./docker/DB_Dockerfile
    container_name: open-source-success-presentation-webapp-db
    ports:
      - "5432:5432"